modLoader="kotlinforforge"
loaderVersion="[5,)"
license="MIT"

[[mods]]
modId="lootbags"
version="3.1.1.4"
displayName="Loot Bags: Patched"
credits="Mina the Engineer (Malorolam), the original author and all contributors to the original mod, and all contributors to this mod."
authors="src_resources, furtabs"
description='''Add loot pouches to entity drops.'''
logoFile = "logo.png"

[[dependencies.lootbags]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lootbags]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1, 1.22)"
    ordering="NONE"
    side="BOTH"
